:toc: auto


= *Domeinregels*

Deze domeinregels zijn gebaseerd op de summiere beschrijving van het probleemdomein en de initiële gebruikersvereisten, alsook de verdere beschrijving in het vraag en antwoord document.

Eenvoudige domeinregels (zoals bv. 'elk lidnummer is uniek') werden niet in dit document opgenomen. Deze werden ondergebracht bij het betroffen element in de klassenbeschrijving.


== *Domeinregels met betrekking op exemplaren*

=== DR_EGE - Exemplaar is Gelijkwaardig met ander Exemplaar

Een exemplaar is gelijkwaardig met een ander exemplaar indien ze allebei dezelfde titel op hetzelfde medium betreffen.

=== DR_EB - Exemplaar is Bruikbaar

Een exemplaar is bruikbaar indien het niet defect en niet gearchiveerd is.

=== DR_EVD - Exemplaar is Verhuurbaar op Dag

Een exemplaar is verhuurbaar op een dag indien het bruikbaar is, die dag niet
verhuurd is en het aantal (andere bruikbare en niet-verhuurde) gelijkwaardige
exemplaren groter of gelijk is aan het aantal (openstaande) passende
concurrerende reservaties die dag.

_(Merk op dat dit betekent dat ofwel álle bruikbare en niet-verhuurde
gelijkwaardige exemplaren op die dag verhuurbaar zijn ofwel geen enkele)_

=== DR_EVP - Exemplaar is Verhuurbaar gedurende Periode

Een exemplaar is verhuurbaar gedurende een periode, als het elke dag in die
periode verhuurbaar is.

=== DR_EMB - Exemplaar is Momenteel Beschikbaar

Een exemplaar is momenteel beschikbaar indien het bruikbaar is en zich op dit
moment in de videotheek bevindt.
_(Merk op dat dit impliceert dat het vandaag niet verhuurd is)._

=== DR_EMG - Exemplaar is Momenteel Gereserveerd

Een momenteel beschikbaar exemplaar is op dit moment gereserveerd indien
het aantal (andere) gelijkwaardige momenteel gereserveerde exemplaren
kleiner is dan het aantal passende concurrende reservaties voor vandaag.

=== DR_EMV - Exemplaar is Momenteel Verhuurbaar

Een exemplaar is momenteel verhuurbaar als het vandaag verhuurbaar en
momenteel beschikbaar is.


[red]#todo : mom. verhuurbaar, mom. gereserveerd sluiten elkaar niet uit zoals het nu
is? en verhuurbaar(vandaag), houdt geen rekening met mom. gereserveerde?#


== *Domeinregels met betrekking op reservaties*

=== DR_REV - Reservatie van Exemplaar voor Volwassenen

Bij het reserveren van een volwassenenfilm wordt gekeken of de klant meerderjarig is op het moment dat de reservatie gemaakt wordt (en niet op de dag waarvoor gereserveerd wordt).

=== DR_RPE - Reservatie en Passende Exemplaren

Een reservatie en een verzameling gelijkwaardige exemplaren zijn passend
indien hun titels en media gelijk zijn.

=== DR_RCR - Reservatie Concurrerende Reservaties

Concurrerende reservaties zijn openstaande reservaties met dezelfde titel,
medium en reservatiedatum combinatie. 

=== DR_RCC - Reservatie Conflict tussen Concurrenten

Er is een conflict bij het nakomen van concurrerende reservaties indien hun
aantal groter is dan het aantal passende bruikbare exemplaren op de
reservatiedatum. Dit geldt ook indien er eigenlijk maar één reservatie is.

=== DR_RVC - Reservatie Voorrangsregel bij een Conflict

In een conflict bij het nakomen van concurrerende reservaties, hebben oudere
reservaties voorrang op jongere reservaties.

[red]#todo : overnemen in V&A!#

=== DR_RER - Reservatie passend Exemplaar Reserveren

Op de dag van de reservatie wordt van zodra het kan nagegaan of een
beschikbaar passend exemplaar gereserveerd moet worden. 

=== DR_RVG - Reservatie is Vandaag Gegarandeerd

Alle (openstaande) concurrerende reservaties zullen gegarandeerd na te komen
zijn, indien hun aantal gelijk is aan het aantal passende gereserveerde
exemplaren.

_(Merk op dat ofwel alle openstaande concurrerende reservaties vandaag
gegarandeerd zullen zijn, ofwel geen enkele)_

=== DR_RKN - Reservatie Keuze exemplaar bij Nakomen

Concurrerende reservaties die niet gegarandeerd na te komen zijn, worden
volgens het principe van 'first come, first served' voldaan.

[red]#todo : overnemen in V&A!#

=== DR_RAP - Reservatie Annulatie Periode

Een reservatie kan ten laatste geannuleerd worden door een klant op de dag
van de reservatie, voor 19u. 

=== DR_RHP - Reservatie Huren Periode

Een niet-geannuleerde reservatie moet op de reservatiedag worden gehuurd.


== *Domeinregels met betrekking op kosten*

=== DR_KVR - Kost van een Vergeten Reservatie

Indien de afhaalperiode van een reservatie verstrijkt zonder dat de klant het
exemplaar heeft gehuurd, wordt de dagprijs van het exemplaar op de
reservatiedatum aangerekend op de lopende rekening van de klant.

=== DR_KKM - Kost Kwijtschelden is steeds Mogelijk

Een medewerker kan steeds beslissen om een kost kwijt te schelden.

=== DR_KEP - Kost van een Exemplaar voor een Periode

De kost van een verhuring over een periode is gelijk aan het product van de
dagprijs voor de eerste dag van de periode en het aantal dagen in die periode.
De dag waarop het exemplaar moet teruggebracht worden telt hierbij niet mee.

=== DR_KED - Kost van een Exemplaar per Dag

De dagprijzen kunnen varieren per soort exemplaar *maar ook per medium*.

De initiële dagprijzen zijn :

* Nieuwe film 3 Euro
* Gewone film 2 Euro
* Kinderfilm 2 Euro
* Volwassenenfilm 2 Euro
* Spelletje 2 Euro

en zijn vooralsnog (!) onafhankelijk van het medium.

=== DR_KLE - Kost voor een Laat Exemplaar

De kost voor een te laat teruggebracht exemplaar komt overeen met het bedrag
van een verhuring voor de dagen dat het exemplaar niet werd teruggebracht.
Bij deze berekening wordt de dagprijs gebruikt op de eerste dag van de
oorspronkelijke verhuring.

=== DR_KTK - Kost wordt vergoed bij Terechte Klacht

Indien een klant een terechte klacht heeft ingediend, krijgt hij de betaalde prijs
van de verhuring van dat exemplaar als tegoed op zijn lopende rekening.

=== DR_KTV - Kost Terugspoelen van een VHS-cassette

De kost voor het terugspoelen van een VHS-cassette bedraagt 0,50 Euro.

=== DR_KGK - Kost Gratis exemplaar Kiezen

Als een klant (een deel van) de rekening wil betaling met een gratis
exemplaar, is dit steeds de dagprijs van het duurste exemplaar op de rekening.


== *Domeinregels met betrekking op rekeningen*

=== DR_AVK - Afrekening Volgorde waarin Kortingen worden toegepast

Om een rekening op te stellen wordt eerst de verjaardagskorting toegepast, wat
een gratis exemplaar kan opleveren. Dan wordt de kinderzondag korting
toegepast. Vervolgens worden alle gratis exemplaren opgebruikt (zie
DR_KGK en DR_AGE). De overblijvende films worden één voor één
afgehandeld (goedkoopste eerst) en meegerekend voor de 10+1 formule.
Indien hierbij een nieuw gratis exemplaar ontstaat wordt dit meteen gebruikt,
behalve als er daarna geen exemplaren meer zijn (dan wordt dit gratis
exemplaar opgespaard).

[red]#todo : nog eens grondig checken en uitwerken met BUC_A#

=== DR_AGV - Afrekening Gratis exemplaar voor Verjaardag

Indien een klant een film huurt op zijn/haar verjaardag krijgt hij/zij een
exemplaar gratis voor één dag, ook als de verjaardag middenin een
verhuurperiode valt (behalve voor een sluitingsdag). Voor te late exemplaren
telt dit niet.

=== DR_AGE - Afrekening Gratis Exemplaar gebruiken

Een gratis exemplaar voor één dag dient zo snel mogelijk gebruikt te worden
(i.e. meteen of bij de eerstvolgende verhuring waarvoor dit kan). Dit kan
gebruikt worden voor een te laat exemplaar.

[red]#todo : toevoegen in V&A dat gratis film kan dienen voor te laat#

=== DR_AKT - Afrekening Korting volgens Tien plus één formule

Telkens de klant een exemplaar huurt (of een reservatie vergeet) telt dit mee
voor deze korting, behalve als het een gratis of een te laat exemplaar betreft.
Eenmaal 10 exemplaren werden gehuurd, levert dit een gratis exemplaar voor
één dag en begint de telling opnieuw bij nul. 

=== DR_AKK - Afrekening Korting wegens KinderZondag

’s Zondags worden kinderfilms en alle spelletjes aan halve dagprijs verhuurd,
ook indien deze zondag middenin een verhuurperiode valt. Voor te late
exemplaren geldt dit echter niet.


== *Domeinregels met betrekking op verhuringen*

=== DR_VUT - Verhuring Uiterste Tijdstip om exemplaar terug te brengen

Een exemplaar dient ten laatste om 18u teruggebracht te worden, de dag na de
laatste betaalde dag van de verhuring.

=== DR_VEV - Verhuur van een Exemplaar voor Volwassenen

Een volwassenenfilm kan enkel door meerderjarigen gehuurd worden (i.e. 18
jaar of ouder). 

=== DR_VPS - Verhuurperiode en SluitingsDagen

Exemplaren moeten steeds tijdig teruggebracht kunnen worden m.b.t.
voorziene sluitingsdagen. De verhuurperiode mag dus niet eindigen op de dag
vóór zo'n sluitingsdag.

[red]#Iets van DR ivm gratis op (on)voorziene sluitingsdagen?#
