==  BUC-KR Klant Registreren

=== Actors
Persoon, *Medewerker*
 
=== Preconditie 
geen

=== Basis pad
. De *Persoon* wil zich registreren als klant van de bank.
. De *Medewerker* vraagt aan de persoon zijn identiteitskaart.
. De *Persoon* geeft de identiteitskaart.
. De *Medewerker* controleert of de *Persoon* aan de vereisten voldoet om klant te mogen worden.
. De *Medewerker* regisreert de *Persoon* zijn gegevens.
*De use case eindigt*

==== Postconditie
De *Persoon* is geregistreert als klant van de bank.

=== Alternatief A: Persoon voldoet niet aan de vereisten
[start=5]
. De *Medewerker* merkt dat de *Persoon* niet voldoet aan de vereisten om klant te worden.
. De *Medewerker* informeert de *Persoon* hierover.
*De use case eindigt*

==== Postconditie
De Persoon is niet geregistreert als klant.

=== Alternatief B: Persoon is al klant van de bank
[start=5]
. De *Medewerker* merkt dat de *Persoon* al een dienst van de bank gebruikt en dus al klant is.
. De *Medewerker* informeert de *Persoon* hierover.
*De use case eindigt*

==== Postconditie
De Persoon was al geregistreert als klant.

=== Representatieve scenario's

==== SC-KR-A001 - Klant registreren
Maarten wil zich als klant registreren bij de VSB-bank. Maarten gaat naar het loket en vraagt om een rekening te openen.
De Medewerker vraagt Maarten zijn ID. Maarten geeft zijn ID.
De medewerker controleert of Maarten aan de vereisten voldoet om klant te mogen worden van de VSB-bank.
De medewerker merkt dat Maarten aan de vereisten voldoet en regisreerd Maarten als klant van de bank.
*De use case eindigt*

==== SC-KR-A002 - Maarten voldoet niet aan de vereisten
Maarten wil zich als klant registreren bij de VSB-bank. Maarten gaat naar het loket en vraagt om een rekening te openen.
De Medewerker vraagt Maarten zijn ID. Maarten geeft zijn ID.
De medewerker controleert of Maarten aan de vereisten voldoet om klant te mogen worden van de VSB-bank.
De medewerker merkt dat Maarten niet aan de vereisten voldoet en deelt dit mee aan Maarten.
*De use case eindigt*

==== SC-KR-A003 - Maarten is al klant van de bank
Maarten wil zich als klant registreren bij de VSB-bank. Maarten gaat naar het loket en vraagt om een rekening te openen.
De Medewerker vraagt Maarten zijn ID. Maarten geeft zijn ID.
De medewerker controleert of Maarten aan de vereisten voldoet om klant te mogen worden van de VSB-bank.
De medewerker merkt dat Maarten al klant is bij de bank.
*De use case eindigt*