=== Vragen

V 1: Wat is het maximum aantal biljetten dat de klant kan storten via de automaat?

V 2: Hoeveel euro kan er afgehaald worden via de automaat?

V 3: Moet je geld hebben om een rekening te openen?

V 4: Komen er extra kosten bij het overschrijven naar een andere bank?

V 5 : Wat als de klant wil stoppen en zijn rekeningen wil overdragen?

V 6: Wat zijn de limieten voor betalingsverrichtingen en hoe te verhogen/verlagen?

V 7: Is het mogelijk om meerdere zichtrekeningen te openen?

V 8: Mag je vanuit een andere bank een spaarrekening openen?

V 9: Kunnen mensen uit het buitenland een rekening openen?

V 10: Moet je in het bezit zijn van een zichtrekening alvorens je een spaarrekening opent?

=== Antwoorden

A 1: Er is geen limiet op het bedrag en/of aantal biljetten dat je kan storten.

A 2: Er is geen bijkomende limiet op afhalingen (er moet natuurlijk genoeg geld op de rekening staan of je kan niet over de kredietlimiet gaan).

A 3 : Neen alsook houdt de bank geen rekening met het inkomen van de klant.

A 4: Neen, momenteel is dit gratis.

A 5: Een rekening kan niet stopgezet worden (niet door de klant en niet door de bank).

A 6: Er zijn momenteel geen limieten voor betalingsverrichtingen.

A 7: Er zijn geen limieten op het aantal rekeningen.

A 8: Neen.

A 9: Neen, onze klant moet een geldig Belgisch rijksregisternummer hebben.

A 10: Ja dit is een vereiste.