= Analyse - Organisatie project
Yanic Inghelbrecht
v2020.10.25.23.59
// toc and section numbering
:toc: preamble
:toclevels: 4
:sectnums: 
:sectlinks:
:sectnumlevels: 4
// source code formatting
:prewrap!:
:source-highlighter: rouge
:source-language: csharp
:rouge-style: github
:rouge-css: class
// inject css for highlights using docinfo
:docinfodir: ../common
:docinfo: shared-head
// folders
:imagesdir: images
:url-verdieping: ../{docname}-verdieping/{docname}-verdieping.adoc
// experimental voor kdb: en btn: macro's van AsciiDoctor
:experimental:

//preamble
[.text-right]
versie {revnumber}

== Introductie

De komende weken zullen jullie in groep aan dit project moeten werken. Vermits dit deels op afstand gebeurt is het niet evident om dit in goede banen te leiden. Dit document beschrijft hoe dit project zal verlopen, wat er van jullie verwacht wordt en wat de spelregels zijn.

== Het verloop van het project

Het project verloopt als volgt :

* Elke projectweek komt er een document online met opdrachten die jullie in groep moeten maken.
* De volgende week krijg je feedback op wat je hebt ingediend en komen er nieuwe opdrachten bij.
* Je past jullie eerdere oplossingen aan (op basis van de feedback die je kreeg) en je maakt ook de nieuwe opdrachten erbij.
* De verbeterde oplossingen voor de oude opdrachten alsook de oplossingen voor de nieuwe opdrachten worden dan samen ingediend.
* De week erna krijg je daarover weer feedback, enz..  Rinse & repeat ;)

**Er is wel elke week verplichte feedback voor alle groep** (evt. online).

De feedback die jullie aan mekaar gaan geven verloopt volgens het volgende patroon, dus vanaf de vierde keer wordt dit patroon herhaald:

* **Week 1: ** G01 met G02 en G03 met G04
* **Week 2: ** G01 met G03 en G02 met G04
* **Week 3: ** G01 met G04 en G02 met G03


=== Deelname aan het groepsgebeuren

Elk groepje heeft een eigen code gekregen (bv. 02) en de indeling kun je opzoeken op Chamilo (forum leerinhouden, groepsindeling per klas). Per groepje is er ook een groepskanaal op MS-Teams voorzien waar jullie toegang toe hebben.

Een belangrijk deel van dit project is werken in groep en communiceren met elkaar. Het is de bedoeling dat je zelf initiatief neemt en niet wacht tot er je iemand werk geeft. Wie niet actief deelneemt mist een deel van het project en dit zal zich ook vertalen in een lagere score op het einde. Het is bovendien ook niet erg netjes tegenover groepsgenoten die wel hun bijdrage leveren.

Als er in jullie groepje spanningen zijn, laat dit dan zo snel mogelijk weten aan je docent. Hoe sneller we het kunnen oplossen, hoe aangenamer de rest van het project zal zijn.

Het spreekt voor zich dat jullie hoffelijk met elkaar omgaan en op je taalgebruik letten.


=== Groepsopdrachten

Voor de groepsopdrachten moeten jullie actief samenwerken en alle groepsleden moeten aanwezig zijn als er gewerkt wordt, dit kan online (bv. via Teams) of fysiek (bv. op de campus of een andere locatie).

Elke week spreken jullie met elkaar af op welke momenten jullie de volgende projectweek aan het project zullen werken, elk *projectmoment* is een slot van 2u. De *eindverantwoordelijke* zorgt dat de afspraken worden gemaakt en post ten laatste zondagavond op welke momenten en waar jullie precies gaan samenzitten. Dit wordt als een bericht in het eigen groepskanaal gepost (bv. kanaal "groep 2" voor groep 2).

Elk groepslid MOET aanwezig zijn op zo'n moment, dus kies een moment waarop iedereen vrij is. Indien iemand toch onverwacht(!) afwezig is op zo'n moment, krijgt hij/zij een nul als persoonlijke weekscore (zie verderop) of de groepsscore als weekscore indien deze afwezigheid gewettigd werd (ibamaflex).


=== Evaluatie

Er zijn 8 projectweken, dus het werk van jullie groepje (bv. 2) zal 8 keer geevalueerd worden. De scores van het andere groepje waarmee jullie samenwerken, hebben geen directe impact op jullie eigen punten.

Elk groepslid heeft 8 weekscores en een score voor de individuele opdrachten die later moeten ingediend worden. Sommige weken tellen zwaarder mee dan andere (afhankelijk van de hoeveelheid werk en de moeilijkheid) en de bijdrage van de individuele opdrachten is zeer beperkt.

Je weekscore is normaliter gewoon jullie groepsscore van die week. Behaalt jullie groep voor een bepaalde week een 7/10, dan behaal jij voor die week normaliter ook 7/10. Tenzij je ongewettigd afwezig was (0/10), of als blijkt dat je niet actief hebt deelgenomen aan het groepsgebeuren.

LET OP : wie meer dan 2x ongewettigd afwezig is, kan niet meer slagen voor dit OLOD en zal het volgend jaar opnieuw moeten proberen.

Aanwezigheid is sowieso verplicht op de feedbackmomenten (elke week!) alsook op de momenten waarop de groep had afgesproken (om de 2 weken, projectmomenten gepost in het groepskanaal).

Ter herhaling uit de studiewijzer : er is geen herkansing mogelijk voor dit OLOD. Als je eindscore onder de helft ligt, zul je dit vak volgend jaar opnieuw moeten doen.


=== Werkverdeling

Jullie werken samen aan het project en jullie werken op dezelfde momenten aan het project. Dus ofwel werken jullie samen online (scherm delen) ofwel zitten jullie samen op dezelfde locatie. Deze projectmomenten zijn op voorhand afgesproken en vastgelegd (ten laatste op zondag).

**Buiten de afgesproken projectmomenten wordt er niet aan het project gewerkt. **

Er is dus geen enkel moment waarop iemand alleen zit te werken en het "later wel zal doormailen als het klaar is".

Per week is er **een eindverantwoordelijke**. Dit is de persoon die de afspraken voor de project momenten regelt en de finale versies van oplossingen verzamelt en indient. Jullie kiezen onderling wie deze taak de volgende week op zich neemt, iedereen moet minstens 1x eindverantwoordelijke zijn.

Let op : **Iedereen moet van elk stukje van de oplossing op de hoogte zijn**. Ook al was je die week geen eindverantwoordelijke of heb je aan een bepaald stukje niet veel meegeholpen, toch moet je de volledige oplossing kennen.

Als je docent jou tijdens een feedbackmoment een vraag stelt over de oplossing, dan is __"Dat weet ik niet, Jeff heeft dat stukje gemaakt"__ geen aanvaardbaar antwoord.


=== Individuele opdrachten

Sommige weken zul je ook opdrachten krijgen die individueel moeten opgelost worden.

**Individuele opdrachten werkt elke student afzonderlijk uit.**

Als er oplossingen gedeeld worden, wordt dit als fraude aanzien en kan er een melding komen bij de fraudecommissie (en dat wil je echt niet).

Je mag elkaar wel helpen en tips geven, maar nooit (stukken van) oplossingen gewoon doorgeven.

Je oplossingen van de individuele opdrachten hou je zelf bij, je zult deze op een later moment nog moeten indienen.


=== Eindverantwoordelijke

Elke week beslist de groep wie de volgende keer de eindverantwoordelijke zal zijn. Deze student regelt de afspraken rond de projectmomenten voor de komende week en post deze ten laatste op zondag in het groepskanaal.

De *eindverantwoordelijke* verzamelt de bijdragen aan de groepsopdrachten en voegt deze samen tot 1 geheel.

Voor het indienen overloopt de eindverantwoordelijke nog eens alle documenten die zullen worden ingediend zodat iedereen akkoord is en weet heeft van wat wordt ingediend. Je zou versteld staan van hoe vaak in vorige jaren er een groep een oude versie indient of bepaalde stukken gewoon vergeet in te dienen.

De eindverantwoordelijke dient in op Chamilo en geeft alle groepsleden een kopie van wat werd ingediend.

De eindverantwoordelijke geeft ook een kopie aan de andere groep waarmee jullie samenwerken aan dezelfde oplossing (even/oneven groepjes), zij zullen dit immers verder moeten afwerken.


=== Verslag

Elke week vullen jullie een verslag aan waarin staat wie wat wanneer gedaan heeft en hoeveel tijd daaraan gespendeerd werd.

De naam van dit verslag is `verslag groep 02.adoc` (02 vervangen door je eigen groep code) en wordt in asciidoc formaat opgesteld.

Bovenaan het verslag staat als titel 'Verslag groep 02' en daaronder een genummerde lijst met jullie namen (alfabetisch op familienaam)

1. Jan 
2. Miet
3. Joris
4. Cornelia

Elke week voegt de eindverantwoordelijke onderaan dit verslag een stuk toe (zie hieronder) met de details voor die projectweek. Na 4 projectweken moeten er dus 4 van die stukken in staan.

Dit helpt de docent om te zien wie wat doet, maar zal jullie ook helpen bij de werkverdeling.

Dit verslag wordt elke week mee ingediend met de rest van jullie documenten.

Je kunt het stuk hieronder uit `organisatie project.adoc` copy/pasten in je eigen verslag en invullen.


== Projectweek : **__nummer invullen__**

Eindverantwoordelijke : **__naam invullen__**

=== Projectmomenten

[%autowidth]
|====
|Datum | Locatie | Aanwezigen | Totale tijd
|====

Afwezigen worden hier genoteerd met vermelding van welk moment ze gemist hebben.


=== Activiteiten per groepslid

==== Jan

**__Hier staat waaraan deze student gewerkt heeft in deze projectweek, inclusief een opsomming van hoeveel tijd waaraan besteed werd__**

==== Miet

**__Hier staat waaraan deze student gewerkt heeft in deze projectweek, inclusief een opsomming van hoeveel tijd waaraan besteed werd__**

==== Joris

**__Hier staat waaraan deze student gewerkt heeft in deze projectweek, inclusief een opsomming van hoeveel tijd waaraan besteed werd__**

==== Cornelia

**__Hier staat waaraan deze student gewerkt heeft in deze projectweek, inclusief een opsomming van hoeveel tijd waaraan besteed werd__**


