= Analyse - Projectweek 05
Yanic Inghelbrecht
v2021.11.22.23.59
// toc and section numbering
:toc: preamble
:toclevels: 4
:sectnums: 
:sectlinks:
:sectnumlevels: 4
// source code formatting
:prewrap!:
:source-highlighter: rouge
:source-language: csharp
:rouge-style: github
:rouge-css: class
// inject css for highlights using docinfo
:docinfodir: ../common
:docinfo: shared-head
// folders
:imagesdir: images
:url-verdieping: ../{docname}-verdieping/{docname}-verdieping.adoc
// experimental voor kdb: en btn: macro's van AsciiDoctor
:experimental:

//preamble
[.text-right]
versie {revnumber}


== Conceptueel Data Model

Een conceptueel data model beschrijft de data uit het probleemdomein, los van enige databank technologie.

Wij (lees : jullie) gaan een **Entiteit/Relatie Model (ERM)** bouwen en documenteren. De documentatie bestaat uit een tekstuele beschrijving van de entiteitsklassen en hun relaties, verduidelijkt met één of meerdere diagrammen (Entiteit/Relatie Diagrammen, ERD).

De tekstuele beschrijving van een ERM geeft een opsomming van alle entiteitsklassen en hun onderlinge relaties. 

Elke *entiteitsklasse* beschrijft de informatie die we over "iets" willen bijhouden. Bijvoorbeeld een entiteitsklasse "Klant" beschrijft het brokje informatie dat we over elke klant willen bijhouden. Andere voorbeelden zijn "Verhuring", "Product", "Reservatie", "Bestelling", ...

Een entiteitsklasse heeft *attributen*, dit zijn de individuele stukjes data die we willen bijhouden. Bijvoorbeeld een entiteitsklasse "Product" zou attributen "code", "beschrijving", "eenheidsprijs" en "btw-percentage" kunnen hebben.

Tussen entiteitsklassen kunnen er *relaties* liggen. Een relatie tussen A en B betekent dat sommige A-dingen gekoppeld zullen zijn aan sommige B-dingen. Bijvoorbeeld, tussen Klant en Reservatie ligt een "Maakt" relatie : sommige klanten zullen reservaties maken.

De tekstuele beschrijving van het ERM geeft gewoon een opsomming van al deze zaken :

* Per entiteitsklasse (welk soort "ding" beschrijft de data?)
** naam
** korte beschrijving, wat stelt dit "ding" voor?
** opsommig van alle attributen
* Per attribuut (welk kenmerk beschrijft de data?)
** naam
** korte beschrijving, wat stelt dit kenmerk voor?
** soort data (tekst, numeriek, foto, ...)
** verplicht of optioneel, uniek of niet
** eventuele andere beperkingen of voorwaarden waaraan het attribuut moet voldoen
* Per relatie tussen 2 entiteitsklassen
** naam
** de rol die entiteitsklasse 1 in de relatie speelt
** de rol die entiteitsklasse 2 in de relatie speelt
** korte beschrijving, wat stelt de relatie tussen die 2 dingen voor?
** cardinaliteit/multipliciteit (bv. 1-op-1, 1-op-N, N-op-M, minstens 0 of minstens 1, ...)
** eventuele andere beperkingen of voorwaarden waaraan de data moet voldoen

Bovenstaande zal je hopelijk bekend voorkomen uit je "Databanken" cursus.

Hoe je dit precies vormgeeft in Asciidoc zul je zelf moeten kiezen, hieronder staat een eenvoudig voorbeeld als startpunt.


=== Entiteitsklasse Klant

Dit is een persoon die reeds een reservatie maakte bij het verhuurbedrijf.

==== attribuut rrnr

Dit is het rijksregisternummer van de klant.

Tekst, verplicht, uniek.

==== attribuut postcode

Dit is het postcode gedeelte van de woonplaats van deze klant.

Tekst, verplicht, niet uniek

=== Relatie : Klant "Maakt" Reservatie (1-N)

De klant voor wie we het product reserveren is degene die de reservatie "maakt".

Elke klant (rol : opdrachtgever) heeft minstens 1 reservatie maar kan meerdere reservaties hebben.

Elke reservatie (rol : reservatie) heeft precies 1 klant als opdrachtgever.


== Taken

Hieronder staan groepsopdrachten en evt. ook individuele opdrachten. Jullie mogen elkaar helpen en elkaar uitleg en hints geven, zolang je maar niet simpelweg elkaars bestanden overkopieert natuurlijk.

Deze week doen we verder aan het "Vreemde Service Bank" (VSB) project, jullie gaan hier meerdere weken aan werken.

[TIP]
====
Zorg dat je nauwgezet alle instructies volgt, ook dat maakt deel uit van jullie evaluatie.
====

=== De juiste folderstructuur voor het vervolg van het groepswerk

De instructies hieronder zijn enkel bedoeld voor de groepsopdrachten, de oplossingen van de individuele opdrachten bewaar je ergens anders op je schijf!

Voeg een nieuwe folder `projectweek-05` toe aan je `project-vsb` folder, daarin komen de bestanden voor deze week terecht.

Het startpunt voor deze week is jullie oplossing van vorige week, dus deze kun je alvast overnemen.


=== Werkverdeling

Jullie groepje moet voor de **volgende projectweek** een eindverantwoordelijke aanduiden, doe dit nu. 

Voor **deze projectweek** hadden jullie vorige keer al een eindverantwoordelijke aangeduid, toch? ;)


=== Feedback op het ingediende groepswerk van vorige week

De docent komt deze week in jullie groep langs om feedback te geven op het groepswerk van vorige week. 

**Iedereen moet aanwezig zijn tijdens deze feedback.** Dus zowel het groepje dat de besproken oplossing vorige week indiende alsook het groepje dat deze week met deze oplossing aan de slag moet.

Je zult bij het verder uitwerken van het project, rekening moeten houden met de feedback die je kreeg. Denk eraan, als analist moet je duidelijk communiceren, open kwesties goed opvolgen en nauwkeurig omgaan met informatie. 

Als je meermaals dezelfde fouten maakt omdat je de feedback niet goed hebt aangewend, dan loopt er jullie groep iets mis qua communicatie.

De verantwoordelijke van vorige week (die de oplossing heeft ingediend) moet de feedback noteren en doorspelen aan de verantwoordelijk van deze week.

De verantwoordelijke van deze week (die met de ingediende oplossing aan de slag moet) moet zelf ook feedback noteren zodat jullie groepje er straks mee aan de slag kan.

Elke verantwoordelijke stopt z'n feedback in een document met naam `feedback over pw04 groep c06.adoc`, waarbij je c06 vervangt door je eigen groepscode.

Deze beide verantwoordelijken wisselen hun feedback uit op het einde van de feedbacksessie, dan is de kans groter dat er niks werd vergeten.

De verantwoordelijken spelen de feedback door aan alle andere groepsleden zodat zij erop kunnen terugvallen bij hun deel van het werk.

**Deze beide feedback documenten worden mee ingediend!**


=== Opdracht 1 (in groep)

Neem in je `projectweek-05` folder het document `vragen voor de opdrachtgever.adoc` over van een vorige keer (projectweek 02).

*Verwijder nu alle vragen van de vorige keer* uit dat document, deze zijn immers al ingediend (en werden reeds beantwoord). 

Bij het uitwerken van de use cases en scenario's de voorbije weken, hebben jullie vast wel nog een paar vragen voor de opdrachtgever.

Zet bovenaan dit leeggemaakte `vragen voor de opdrachtgever.adoc` document je groepscode (bv. groep A5) en schrijf er minstens *3* nieuwe (en zinvolle!) vragen in.

Dit moeten vragen zijn die iets verduidelijken uit het probleemdomein (bv. "is er commentaar mogelijk bij een storting?"), het mogen dit keer geen vragen meer zijn die de omvang van het project verkennen ("kun je ook een lening afsluiten?").


=== Opdracht 2 (in groep)

Deze week worden de BUCs voor onderstaande taken HERWERKT (**incl. scenario's en domeinregels**) op basis van de feedback die je kreeg.

* Geld Storten
* Geld Afhalen
* Rekening Openen
* Geld overschrijven Intern


=== Opdracht 3 (in groep)
	
We werken deze week een nieuwe taak "Klant registreren" uit. **Voeg een bestand `buc-kr.adoc` toe aan jullie `/bucm` folder waarin je deze taak uitwerkt.**

Bij het registreren van een klant controleert de medewerker eerst of de persoon voldoet aan de vereisten om klant te mogen worden. Daarna registreert de medewerker de persoonsgegevens waardoor die persoon "officieel" klant is geworden bij de bank. Dit identificeert die persoon meteen ook als klant van de bank natuurlijk.


=== Opdracht 4 (in groep)

**Maak een bestand `erm.adoc` in de `/cdm` folder.**

In dit bestand beschrijf je jullie conceptueel data model. In het `erm.adoc` document geef je een opsomming van alle entiteitsklassen en hun attributen, alsook de relaties tussen de entiteitsklassen.

Voolopig beperken we ons tot een data model dat (enkel) de data voor onderstaande drie taken kan beschrijven :

* Klant identificeren
* Zichtrekening openen (geen spaarrekeningen, doe voorlopig alsof die niet bestaan)
* Geld afhalen

Kijk dus naar de representatieve scenario's van de overeenkomstige BUC's en de data in jullie __domain sample__. Jullie conceptueel data model moet immers deze data kunnen beschrijven!

Beperk je tot de data die nodig is bij de drie gevraagde taken. Bijvoorbeeld, in BUC-KR wordt o.a. de postcode geregistreerd maar omdat die taak hier niet gevraagd is zal je data model voorlopig niets over postcodes vertellen. Volgende week zullen we het data model uitbreiden naar alle taken.


=== Verslag

De eindverantwoordelijke zal weerom het `verslag groep c06.adoc` document moeten opstellen en invullen voor deze week. Denk eraan dat je voor deze week een sectie moet *toevoegen* en de secties van de vorige weken in het document blijven staan.

De ganse groep zal ook samen de finale versie overlopen van alle documenten alvorens ze in te dienen.

Het verslag van de andere groep dien je niet mee in en je combineert ze ook niet samen in hetzelfde verslag!


== Indienen

De eindverantwoordelijke overloopt met de groep nog eens de inhoud van de volgende files in de projectweek folder :

* `feedback over pw04 groep c05.adoc` (feedback document van de ene groep)
* `feedback over pw04 groep c06.adoc` (feedback document van de andere groep)
* `verslag groep c06.adoc` (waarbij je c06 vervangt door je eigen groep code)
* `definitieve vragen en antwoorden.adoc`
* `vragen voor de opdrachtgever.adoc` (nieuwe inhoud)
* `cdm/domain-sample.adoc`
* `cdm/erm.adoc` (nieuw)
* `bucm/buc-ki.adoc`
* `bucm/buc-kr.adoc` (nieuw)
* `bucm/buc-goi.adoc` 
* `bucm/buc-gs.adoc` 
* `bucm/buc-ga.adoc` 
* `bucm/buc-zo.adoc` + `bucm/buc-so.adoc` of `bucm/buc-ro.adoc`
* `bucm/domeinregels.adoc`

Deze file stop je vervolgens in een zip bestand met naam `groep c06 projectweek-04.zip` (waarbij je c06 vervangt door je eigen groep code).


[IMPORTANT]
====
Als ik jullie zip file opendoe, wil ik enkel de `projectweek-05` folder zien, geen andere files!

Die andere files zitten immers *_in_* die `projectweek-05` folder in je zip file.

Ik wil ook geen `__MACOSX` of `.DS_Store` drolletjes tegenkomen in de zip file.
====

Deze zip file wordt ingediend op Chamilo, ten laatste de dag VOOR de volgende feedback sessie (de volgende feedbacksessie is normaliter op dezelfde dag volgende week). 

Is jullie volgende feedbacksessie bv. volgende week woensdag, dan moet je oplossing ten laatste volgende week dinsdag op Chamilo ingediend worden.