== BUC-GOI Geld OVerschrijveen Intern

=== Actoren

* Klant en medewerker

=== Precondities 

* Bankkaart hebben

=== Basis pad 

. Klant wenst geld over te schrijven
. Klant geeft ID aan medewerker
. Klant geeft rekeningnummer van de ontvanger
. Klant geeft gewenste bedrag in om over te schrijven
. Klant ondertekent de bevestiging
. Medewerker schrijft het gewenste bedrag over
. Klant kiest of hij/zij een ticket wilt
. Klant neemt bankkaart terug

=== Postcondities

* Succesvol geld overgeschreven

=== Alternatieve paden

* 2.1  ID vervallen
* 2.1a Use case eindigt
* 3.1  Foutief rekeningnummer
* 3.1a Use case eindigt
* 4.1  Klant heeft niet genoeg saldo DR
* 4.1a Use case eindigt

link:domeinregels.adoc[Domeinregels]


== Scenario's

=== S1 Basis Pad

Klant 1 wilt geld overschrijven en gaat naar de bank. Klant 1 geeft zijn iD aan de medewerkster. Medewerkster controlleerd het ID. Klant 1 geeft het rekeningnummer van de ontvanger aan de medewerkster en kiest het gewenste bedrag. Klant 1 ondertekent de bevestiging. Medewerkster vraagt aan klant 1 of hij/zij een ticket wilt. Use case eindigt.

=== S2 Alternatief Pad 2.1

Klant 1 wilt geld overschrijven en gaat naar de bank. Klant 1 geeft zijn iD aan de medewerkster. Medewerkster controlleerd het ID. Het ID is niet geldig. Use case eindigt.

=== S3 Alternatief Pad 3.1

Klant 1 wilt geld overschrijven en gaat naar de bank. Klant 1 geeft zijn iD aan de medewerkster. Medewerkster controlleerd het ID. Klant 1 geeft het rekeningnummer van de ontvanger. Rekeningnummer is niet geldig. Use case eindigt.

=== S4 Alternatief Pad 4.1

Klant 1 wilt geld overschrijven en gaat naar de bank. Klant 1 geeft zijn iD aan de medewerkster. Medewerkster controlleerd het ID. Klant 1 geeft het rekeningnummer van de ontvanger aan de medewerkster en kiest het gewenste bedrag. Klant 1 heeft niet genoeg saldo. Use case eindigt.