= Domain Rules (DR)
Yanic Inghelbrecht
v2021.12.03.23.59
// toc and section numbering
:toc: preamble
:toclevels: 4
// geen auto section numbering voor oefeningen (handigere titels en toc)
//:sectnums:  
:sectlinks:
:sectnumlevels: 4
// source code formatting
:prewrap!:
:source-highlighter: rouge
:source-language: csharp
:rouge-style: github
:rouge-css: class
// inject css for highlights using docinfo
:docinfodir: ../common
:docinfo: shared-head
// folders
:imagesdir: images
// experimental voor kdb: en btn: macro's van AsciiDoctor
:experimental:

//preamble
[.text-right]
versie {revnumber}


== Domeinregels met betrekking op verhuringen

=== DR-VEV : Verhuur van een Exemplaar voor Volwassenen

Een volwassenenfilm kan enkel door meerderjarigen gehuurd worden (i.e. 18 jaar of ouder). 

=== DR-VPS : Verhuurperiode en SluitingsDagen

Exemplaren moeten steeds tijdig teruggebracht kunnen worden m.b.t. voorziene sluitingsdagen. De verhuurperiode mag dus niet eindigen op de dag vóór zo'n sluitingsdag. 

** TODO : Iets van DR nodig ivm gratis op (on)voorziene sluitingsdagen? **


== Domeinregels met betrekking op exemplaren

=== DR-EVP : Exemplaar is Verhuurbaar gedurende Periode

Een exemplaar is verhuurbaar gedurende een periode, als het elke dag in die periode verhuurbaar is.

=== DR-EVD : Exemplaar is Verhuurbaar op Dag

Een exemplaar is verhuurbaar op een dag indien het bruikbaar is, die dag niet verhuurd is en het aantal (andere bruikbare en niet-verhuurde) gelijkwaardige exemplaren groter of gelijk is aan het aantal (openstaande) passende concurrerende reservaties die dag.

__(Merk op dat dit betekent dat ofwel álle bruikbare en niet-verhuurde gelijkwaardige exemplaren op die dag verhuurbaar zijn ofwel geen enkele)__

=== DR-EB : Exemplaar is Bruikbaar

Een exemplaar is bruikbaar indien het niet defect en niet gearchiveerd is.

=== DR-EMB : Exemplaar is Momenteel Beschikbaar

Een exemplaar is momenteel beschikbaar indien het bruikbaar is en zich op dit moment in de videotheek bevindt. (Merk op dat dit impliceert dat het vandaag niet verhuurd is).

=== DR-EMG : Exemplaar is Momenteel Gereserveerd

Een momenteel beschikbaar exemplaar is op dit moment gereserveerd indien het aantal (andere) gelijkwaardige momenteel gereserveerde exemplaren kleiner is dan het aantal passende concurrende reservaties voor vandaag.

=== DR-EMV : Exemplaar is Momenteel Verhuurbaar

Een exemplaar is momenteel verhuurbaar als het vandaag verhuurbaar en momenteel beschikbaar is.

**TODO : mom. verhuurbaar, mom. gereserveerd sluiten elkaar niet uit zoals het nu is? en verhuurbaar(vandaag), houdt geen rekening met mom. gereserveerde?**


== Domeinregels met betrekking op reservaties

=== DR-RPE : Reservatie en Passende Exemplaren

Een reservatie en een verzameling gelijkwaardige exemplaren zijn passend indien hun titels en media gelijk zijn.

=== DR-RCR : Reservatie Concurrerende Reservaties

Concurrerende reservaties zijn openstaande reservaties met dezelfde titel, medium en reservatiedatum combinatie


== Domeinregels met betrekking op kosten

=== DR-KEP : Kost van een Exemplaar voor een Periode

De kost van een verhuring over een periode is gelijk aan het product van de dagprijs voor de eerste dag van de periode en het aantal dagen in die periode. De dag waarop het exemplaar moet teruggebracht worden telt hierbij niet mee.
